package com.revenera.gcs.implementor.diag;

import com.flexnet.external.type.*;
import com.flexnet.external.webservice.keygenerator.LicGeneratorException;
import com.revenera.gcs.AppContext;
import com.revenera.gcs.implementor.GeneratorBase;
import com.revenera.gcs.implementor.GeneratorImplementor;
import com.revenera.gcs.utils.Serializer;

import java.time.Instant;
import java.util.ArrayList;

@GeneratorImplementor(technologyId = "DEF", technologyName = "Unimplemented License Technology", isDefault = true)
public final class DiagnosticLicenseGenerator extends GeneratorBase {

  @Override
  public Status validateProduct(final ProductRequest product) {

    AppContext.injectRequest(product);
    return AppContext.injectResponse(Status.class, new Status() {
      {
        this.message = Serializer.safeSerializeYaml(product);
        this.code = 0;
      }
    });

  }

  @Override
  public Status validateLicenseModel(final LicenseModelRequest request) throws LicGeneratorException {

    AppContext.injectRequest(request);
    return AppContext.injectResponse(Status.class, new Status() {
      {
        this.message = Serializer.safeSerializeYaml(request);
        this.code = 0;
      }
    });

  }

  @Override
  public GeneratorResponse generateLicense(GeneratorRequest request) throws LicGeneratorException {

    AppContext.injectRequest(request);
    return AppContext.injectResponse(GeneratorResponse.class, new GeneratorResponse() {
      {
        this.licenseFiles = makeLicenseFiles(
            request.getLicenseTechnology().getLicenseFileDefinitions(),
            Serializer.safeSerializeYaml(request),
            null);

        setLicenseText("#Generated by external server at " + Instant.now().toString());

        setLicenseFileName("nofile.txt");
      }
    });

  }

  @Override
  public ConsolidatedLicense consolidateFulfillments(final FulfillmentRecordSet request) throws LicGeneratorException {

    AppContext.injectRequest(request);
    return AppContext.injectResponse(ConsolidatedLicense.class, new ConsolidatedLicense() {
      {
        this.licenseFileName = "license";
        this.licenseText = Serializer.safeSerializeYaml(request);
      }
    });

  }

  @Override
  public LicenseFileDefinitionMap generateLicenseFilenames(final GeneratorRequest request) throws LicGeneratorException {

    AppContext.injectRequest(request);
    return AppContext.injectResponse(LicenseFileDefinitionMap.class, new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    });

  }

  @Override
  public LicenseFileDefinitionMap generateConsolidatedLicenseFilenames(final ConsolidatedLicenseResquest request) throws LicGeneratorException {

    AppContext.injectRequest(request);

    return AppContext.injectResponse(LicenseFileDefinitionMap.class, new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    });

  }

  @Override
  public String generateCustomHostIdentifier(final HostIdRequest request) throws LicGeneratorException {

    AppContext.injectRequest(request);

    return Serializer.safeSerializeYaml(request);

  }
}

