package com.revenera.gcs.implementor;

import com.flexnet.external.type.*;
import com.flexnet.external.webservice.keygenerator.LicGeneratorException;
import com.revenera.gcs.utils.GeneratorImplementor;
import com.revenera.gcs.utils.Serializer;

import java.time.Instant;
import java.util.ArrayList;

@GeneratorImplementor(technologyId = "DEF", technologyName = "Default License Technology", isDefault = true)
public final class DefaultLicenseGenerator extends GeneratorBase {

  @Override
  public Status validateProduct(final ProductRequest product) {
    logger.in();
    return new Status() {
      {
        this.message = Serializer.safeSerializeYaml(product);
        this.code = 0;
      }
    };
  }

  @Override
  public Status validateLicenseModel(final LicenseModelRequest request) throws LicGeneratorException {
    logger.in();
    return new Status() {
      {
        this.message = Serializer.safeSerializeYaml(request);
        this.code = 0;
      }
    };
  }

  @Override
  public GeneratorResponse generateLicense(GeneratorRequest request) throws LicGeneratorException {
    logger.in();
    return new GeneratorResponse() {
      {
        this.licenseFiles = makeLicenseFiles(
            request.getLicenseTechnology().getLicenseFileDefinitions(),
            Serializer.safeSerializeYaml(request),
            null);

        setLicenseText("#Generated by external server at " + Instant.now().toString());

        setLicenseFileName("nofile.txt");
      }
    };
  }

  @Override
  public ConsolidatedLicense consolidateFulfillments(final FulfillmentRecordSet request) throws LicGeneratorException {
    logger.in();
    return new ConsolidatedLicense() {
      {
        this.licenseFileName = "license";
        this.licenseText = Serializer.safeSerializeYaml(request);
      }
    };
  }

  @Override
  public LicenseFileDefinitionMap generateLicenseFilenames(final GeneratorRequest request) throws LicGeneratorException {
    logger.in();
    return new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    };
  }

  @Override
  public LicenseFileDefinitionMap generateConsolidatedLicenseFilenames(final ConsolidatedLicenseResquest request) throws LicGeneratorException {
    logger.in();
    return new LicenseFileDefinitionMap() {
      {
        this.item = new ArrayList<>();
      }
    };
  }

  @Override
  public String generateCustomHostIdentifier(final HostIdRequest request) throws LicGeneratorException {
    logger.in();
    return Serializer.safeSerializeYaml(request);
  }
}

